// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjm14oI7wZEnCVWqSx5YCbgignMEMWUk',
    appId: '1:1033581757125:web:dda39bcf14ad5ad6a026ac',
    messagingSenderId: '1033581757125',
    projectId: 'note-vault-eefb1',
    authDomain: 'note-vault-eefb1.firebaseapp.com',
    storageBucket: 'note-vault-eefb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhBb30xSMSKJegLnbT4jdotRwO4H1_14o',
    appId: '1:1033581757125:android:a8a543569a3f7a0ba026ac',
    messagingSenderId: '1033581757125',
    projectId: 'note-vault-eefb1',
    storageBucket: 'note-vault-eefb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6mnXd6C1wgvh6m0mPTF0hhQtKGp4dTJ0',
    appId: '1:1033581757125:ios:c8c2e723b2d69583a026ac',
    messagingSenderId: '1033581757125',
    projectId: 'note-vault-eefb1',
    storageBucket: 'note-vault-eefb1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6mnXd6C1wgvh6m0mPTF0hhQtKGp4dTJ0',
    appId: '1:1033581757125:ios:c8c2e723b2d69583a026ac',
    messagingSenderId: '1033581757125',
    projectId: 'note-vault-eefb1',
    storageBucket: 'note-vault-eefb1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIjm14oI7wZEnCVWqSx5YCbgignMEMWUk',
    appId: '1:1033581757125:web:ad524ee22bfc6c9ba026ac',
    messagingSenderId: '1033581757125',
    projectId: 'note-vault-eefb1',
    authDomain: 'note-vault-eefb1.firebaseapp.com',
    storageBucket: 'note-vault-eefb1.appspot.com',
  );
}
